default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost
  port: 5432

queue_default: &queue_default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: events_task_development

queue_development:
  <<: *queue_default
  database: events_task_queue_development

test:
  <<: *default
  database: events_task_test

queue_test:
  <<: *queue_default
  database: events_task_queue_test

production:
  <<: *default
  database: events_task_production
  username: <%= ENV["EVENTS_TASK_DATABASE_USER"] || "postgres" %>
  password: <%= ENV["EVENTS_TASK_DATABASE_PASSWORD"] %>
  host: <%= ENV["EVENTS_TASK_DATABASE_HOST"] %>

queue_production:
  <<: *queue_default
  database: events_task_queue_production
  username: <%= ENV["EVENTS_TASK_QUEUE_DATABASE_USER"] || "postgres" %>
  password: <%= ENV["EVENTS_TASK_QUEUE_DATABASE_PASSWORD"] %>
  host: <%= ENV["EVENTS_TASK_QUEUE_DATABASE_HOST"] %>